### ISSUE TITLE
Server not reading params.switch from POST

### ISSUE THREAD

**Issue by kstunger** [DoganM95/Ewelink-rest-api-server#5]
When posting to the Docker container using a body such as:
```
{  
    "params": {
        "switch": "on",
    },
    "deviceid": "xxxxxxx"
}
```

The server crashes and logs the following:
```Ewelink api server listening on http://localhost:3000
file:///usr/src/app/server/server.js:31
    const requestedActionOnDevice = req.body.params.switch != undefined && req.body.params.switch != "" ? String(req.body.params.switch) : undefined;
                                                    ^

TypeError: Cannot read property 'switch' of undefined
    at file:///usr/src/app/server/server.js:31:53
    at Layer.handle [as handle_request] (/usr/src/app/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/server/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/server/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/usr/src/app/server/node_modules/body-parser/lib/types/json.js:119:7)
    at Layer.handle [as handle_request] (/usr/src/app/server/node_modules/express/lib/router/layer.js:95:5)```

**Comment by kstunger** [comment]
Turns out the issue was with the `Content-Type` header in my POST.  This needs to be set to `application/json` and not `text/plain` as I had it.

**Comment by DoganM95** [comment]
Glad you figured out. Always feel free to report bugs/feature requests etc :)
